apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
spec:
  selector:
    matchLabels:
      app: post
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: rezacomplete/post
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default